### ISSUE TITLE
need for a cron job

### ISSUE THREAD

**Issue by hardcod3r** [aalfiann/reSlim#3]
is there any way to set a cron job ? not accessing by web

**Comment by aalfiann** [comment]
Hmm, 

Did you mean set cron job like task scheduler? In this default project there is no feature about cron job and we have no plan for it.

Just create your own module. You can read tutorial how to create new module from this [Wiki](https://github.com/aalfiann/reslim/wiki).

**Comment by hardcod3r** [comment]
Thanks for your reply. I created my own model but i was need to run some classes only by cli. anyway.. i ll give a try. thanks
